config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  post 'procesar-pago', to: "payments#create"
  get 'pages/search', to: 'pages#search'
  get 'products/search', to: 'products#search'
  get '/info', to: 'pages#info'

  resources :divisions, except: :destroy
  resources :categories, except: :destroy
  resources :products
  resources :users, only: [:index, :show]
  resources :line_items
  resources :carts do
    collection do
      post :carts_delete
    end
  end
  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: :new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  has_many :products
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user.admin?
      @users = User.all
    else
      redirect_to root_path
      flash[:notice] = "Accesso denegado!"
    end
  end

  def show
    @user = User.find(params[:id])
    @products = Product.all
  end
end

app/views/users/_profile.html.erb
<div class="profile-user-container">
  <h3 class= "product-user-title">TUS DATOS</h3>
  <h2>Nombre legal</h2>
  <p><%= @user.name %></p>
  <h2>Telefono</h2>
  <p><%= @user.phone %></p>
  <h2>Direción</h2>
  <p><%= @user.address %></p>
  <h2>Ciudad</h2>
  <p><%= @user.city %></p>
  <h2>Dirección de correo electrónico</h2>
  <p><%= @user.email %></p>
  <div class="pb-5">
   <%= link_to 'Editar Perfil', edit_user_registration_path, class: "btn btn-dark btn-lg btn-block" %>
 </div>

</div>

app/views/users/_user_admin.html.erb
<div class="user-show-wrapper">
  <div class="text-center">
    <h2>Bienvenido <%= current_user.email %></h2>
  </div>
  <%= link_to 'Crear Categoria Principal', new_division_path, class: 'btn btn-dark btn-lg btn-block' %>
  <%= link_to 'Ver Categoria Principal', divisions_path, class: 'btn btn-primary btn-lg btn-block' %>
  <%= link_to 'Crear Categoria', new_category_path, class: 'btn btn-dark btn-lg btn-block' %>
  <%= link_to 'Ver Categorias', categories_path, class: 'btn btn-primary btn-lg btn-block' %>
  <%= link_to 'Crear Producto', new_product_path, class: 'btn btn-dark btn-lg btn-block'  %>
  <%= link_to 'Inventario de Productos', products_path, class: 'btn btn-primary btn-lg btn-block'  %>
  <%= link_to 'Ver Ordenes', orders_path, class: 'btn btn-danger btn-lg btn-block'  %>
  <%= link_to 'Ver Usuarios', users_path, class: 'btn btn-primary btn-lg btn-block'  %>
</div>

app/views/users/_user_orders.html.erb
<div class="user-order-container">
  <% if current_user.orders.present? %>
  <h3 class= "product-user-title">HISTORIAL DE PEDIDOS</h3>
  <table class="table table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <th scope="col">Fecha</th>
        <th scope="col">Precio</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% orders = @user.orders.filter { |order| order.state == 'Encargado' } %>
      <% orders.reverse_each do |order| %>
      <tr>
        <td><%= order.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= order.total %></td>
        <td><%= link_to 'Ver orden', order_path(order) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
  <h3 class= "product-user-title">HISTORIAL DE PEDIDOS</h3>
  <p style="font-size: 13px; color: grey;">No hemos registrado ningún pedido para esta cuenta</p>
  <%= link_to 'Empezar a comprar', root_path, class: 'btn-gradient'  %>
  <% end %>
</div>

app/views/users/_user_product.html.erb
<h2 class= "product-user-title">PRODUCTOS RECOMENDADOS</h2>
<div class= "category-container">
  <% @products.first(8).uniq(&:title).each do |product| %>
  <%= render 'shared/cards', product: product %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'shared/navbar' %>
<div class="users-container">
  <table class="table table-striped ">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Usuarios</th>
        <th scope="col">Ordenes</th>

        <th scope="col">Fecha de inicio</th>
        <th scope="col">Administrador</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user_path(user) %></td>
        <td><%= user.orders.count %></td>
        <td><%= user.created_at.strftime('%d/%m/%Y') %></td>
        <% if user.admin? %>
        <td>SI</td>
        <% else %>
        <td>NO</td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>
<br><br>
<% if @user == current_user %>
<% if current_user.admin? %>
<%= render 'user_admin' %>
<% else %>
<% end %>
<div class="user-show-container">
  <div class="user-show-title d-flex justify-content-between align-items-center">
    <h2><%= @user.email %></h2>
    <h3> <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%></h3>
  </div>
</div>
<div class="about-container">
  <div class="nav-tab">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Mi cuenta</a>
      <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Historial de Pedidos</a>
      <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Datos Personales</a>
    </div>
  </div>
  <div class="nav-tab-content">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab"><%= render 'user_product' %></div>
      <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab"><%= render 'user_orders' %></div>
      <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab"><%= render 'profile' %></div>
    </div>
  </div>
</div>


<% else %>
<%= render 'shared/denied' %>
<% end %>