config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  post 'procesar-pago', to: "payments#create"
  get 'pages/search', to: 'pages#search'
  get 'products/search', to: 'products#search'
  get '/info', to: 'pages#info'

  resources :divisions, except: :destroy
  resources :categories, except: :destroy
  resources :products
  resources :users, only: [:index, :show]
  resources :line_items
  resources :carts do
    collection do
      post :carts_delete
    end
  end
  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: :new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/division.rb
class Division < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :categories

  validates :title, presence: true
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_division, only: [:show, :update]

  def index
  end

  def show
    categories = @division.categories
    @products = Product.where(category_id: categories).page params[:page]
  end

  def new
    @division = Division.new
  end

  def create
    @division = Division.new(division_params)
    if @division.save
      redirect_to division_path(@division)
    else
      render :new
    end
  end

  def edit
    if current_user.admin?
      @division = Division.friendly.find(params[:id])
    else
      redirect_to root_path
      flash[:notice] = "Accesso denegado!"
    end
  end

  def update
    @division.update(division_params)
    redirect_to division_path(@division)
  end

  private

  def set_division
    @division = Division.friendly.find(params[:id])
  end

  def division_params
    params.require(:division).permit(:title, :photo)
  end
end

app/views/divisions/_form.html.erb
<%= simple_form_for @division do |f| %>
<p>Titulo</p>
<%= f.input :title, label: false %>
<p>Foto (poner el link de la foto)</p>
<%= f.input :photo, label: false %>
<%= f.submit 'Create Categoria Principal', class: 'btn btn-dark btn-block' %>
<% end %>

app/views/divisions/edit.html.erb
<%= render 'shared/navbar' %>
<br><br><br>
<div class="product-form">
  <h3><%= link_to 'Volver a la pagina principal', root_path  %></h3>
  <h2>Editar Categoria Principal</h2>
  <%= render 'form' %>
</div>

app/views/divisions/index.html.erb
<%= render 'shared/navbar' %>
<% if current_user.admin? %>
<br><br>
<div class="container text-center mt-5">
  <h2>Categorias Principales</h2>
  <table class="table table-striped table-bordered ">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @divisions.each do |division| %>
      <tr>
        <th><%= division.title%></th>
        <td><%= link_to 'Editar', edit_division_path(division)  %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pt-3">
    <%= link_to 'Crear Categoria Principal', new_division_path, class: 'btn btn-primary btn-block' %>
    <br>
    <%= link_to 'Volver', :back, class: 'btn btn-danger btn-block' %>
  </div>
</div>
<% else %>
<%= link_to 'Volver', root_path %>
<% end %>

app/views/divisions/new.html.erb
<%= render 'shared/navbar' %>
<br><br><br>
<div class="product-form">
  <h3><%= link_to 'Volver a la pagina principal', root_path  %></h3>
  <h2>Crear Categoria Principal (no crear muchas)</h2>
  <%= render 'form' %>
</div>

app/views/divisions/show.html.erb
<%= render 'shared/navbar' %>
<div class="division-banner d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @division.photo %>');">
  <div>
    <h2><%= @division.title %></h2>
  </div>
</div>
<div class="division-wrapper">
  <section id="category-list">
    <div class="categories-list">
      <div class="d-none d-md-block">
        <h2>Categorias:</h2>
      </div>
      <% @division.categories.each do |category| %>
      <p><%= link_to category.title , category_path(category)  %></p>
      <% end %>
    </div>
  </section>
  <section id="division-product-container">
    <div class="division-container">
      <% @products.uniq(&:title).each do |product| %>
      <%= render 'shared/cards', product: product %>
      <% end %>

    </div>
    <div class="text-center">
      <%= paginate @products %>
    </div>
  </section>
</div>
<%= render 'shared/footer' %>