config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  post 'procesar-pago', to: "payments#create"
  get 'pages/search', to: 'pages#search'
  get 'products/search', to: 'products#search'
  get '/info', to: 'pages#info'

  resources :divisions, except: :destroy
  resources :categories, except: :destroy
  resources :products
  resources :users, only: [:index, :show]
  resources :line_items
  resources :carts do
    collection do
      post :carts_delete
    end
  end
  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: :new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_cards.html.erb
<div class="product-card-wrapper">
  <%= link_to product_path(product) do %>
  <div class="product-card">
    <% product.photos.first(1).each do |photo| %>
    <%= cl_image_tag photo.key%>
    <% end %>
    <p><%= product.title %></p>
    <% if product.stock < 1 %>
    <h4 style="color: black;">AGOTADO</h4>
    <% else %>
    <div class="d-flex justify-content-center">
      <% if product.sale.present? %>
      <h4 style="color: red;"><%= humanized_money_with_symbol(product.price) %></h4>
      <h4 style="padding-left: 10px; text-decoration: line-through; color: lightgrey;">$<%= product.sale %></h4>
      <% else %>
      <h4><%= humanized_money_with_symbol(product.price) %></h4>
      <% end %>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_denied.html.erb
<div class="denied-wrapper d-flex justify-content-center align-items-center" style="height: 100vh; background: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1579282940892-6152e6e80c52?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80); background-size: cover; background-position: center;" >
  <div class="denied-container">
    <h2 style="font-weight: bold;
    color: white;
    font-size: 36px;">Acceso Denegado</h2>
    <%= link_to 'Volver', :back, class: 'btn btn-lg btn-danger btn-block'  %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <h4>Pedidos por WhatsApp:</h4>
  <h4>Plaza Sarmiento: <a href="https://api.whatsapp.com/send?phone=5493364595450" target="_blank" rel="noopener noreferrer">336-4595450</a>
  </h4>
  <h4>Tilo Catedral: <a href="https://api.whatsapp.com/send?phone=5493364495676" target="_blank" rel="noopener noreferrer">3364495676</a>
  </h4>
  <br>
  <h2><i class="far fa-copyright"></i> Tilo Tienda Natural</h2>
  <h3>Made by - <%= link_to 'GV', 'http://www.gvweb.ar/', target: '_blank'  %></h3>
</div>

app/views/shared/_home_cards.html.erb
<div class="product-card home-card">
  <%= link_to product_path(product) do %>
  <% product.photos.first(1).each do |photo| %>
  <%= cl_image_tag photo.key%>
  <% end %>
  <p><%= product.title.truncate(30) %></p>
  <% if product.stock < 1 %>
  <h4 style="color: black;">AGOTADO</h4>
  <% else %>
  <div class="d-flex justify-content-center">
    <% if product.sale.present? %>
    <h4 style="color: red;"><%= humanized_money_with_symbol(product.price) %></h4>
    <h4 style="padding-left: 10px; text-decoration: line-through; color: lightgrey;">$<%= product.sale %></h4>
    <% else %>
    <h4><%= humanized_money_with_symbol(product.price) %></h4>
    <% end %>
  </div>
  <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" id="guillo" onclick="onClick()">
    <span class="menu">
      <svg width="30" height="18" viewBox="0 0 30 18" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect width="30" height="2.57143" fill="white"/>
        <rect y="7.71429" width="18.2609" height="2.57143" fill="white"/>
        <rect y="15.4286" width="24.7826" height="2.57143" fill="white"/>
      </svg>
    </span>
    <span class="transparent cross">
      <svg width="30" height="29" viewBox="0 0 30 29" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect width="37.0786" height="3" transform="matrix(0.691384 0.722487 -0.805471 0.592635 4.36426 0)" fill="white"/>
        <rect width="37.0786" height="3" transform="matrix(0.691384 -0.722487 0.805471 0.592635 0 26.7888)" fill="white"/>
      </svg>
    </span>
  </button>
  <div>
    <%= link_to root_path, class: 'navbar-brand' do  %>
    <img src="https://res.cloudinary.com/dye9yotct/image/upload/v1689603490/LogosTilo-04_1_fdpt4a.png" alt="" style="width: 120px; height: 62px; object-fit: cover;">
    <% end %>
  </div>

  <div class="d-lg-none magnify">
   <div class="d-flex align-items-center justify-content-end">
    <div class="cart-item">
      <% if total_cart_items %>
      <%= link_to cart_path(@cart) do %>
      <span class="icon is-small">
        <i class="fas fa-shopping-basket "></i>
      </span>
      <span><%= cart_count_over_one %></span>
      <% end %>
      <% end %>
    </div>
    <div class="cart-search">
      <%= link_to pages_search_path do  %>
      <i class="fas fa-search"></i>
      <% end %>
    </div>
  </div>
</div>

<div class="collapse navbar-collapse" id="navbarNav">
  <% @divisions.each do |division| %>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to division.title, division_path(division), class: 'nav-link' %>
    </li>
    <% end %>
     <li class="nav-item">
      <%= link_to "Info. Importante", info_path , class: 'nav-link'%>
    </li>
    <li class="nav-item d-lg-none">
      <% if user_signed_in? %>
      <%= link_to "Perfil", user_path(current_user), class: "nav-link" %>
      <% else %>
      <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
      <% end %>
    </li>
  </ul>
</div>
<div class="d-none d-lg-block">

  <div class="d-flex align-items-center">
    <div class="cart-item-lg">
      <% if total_cart_items %>
      <%= link_to cart_path(@cart) do %>
      <span class="icon is-small">
        <i class="fas fa-shopping-basket"></i>
      </span>
      <span><%= cart_count_over_one %></span>
      <% end %>
      <% end %>
    </div>
    <div>
      <%= link_to pages_search_path do  %>
      <i class="fas fa-search" style="color: white; font-size: 24px;"></i>
      <% end %>
      <% if user_signed_in? %>
      <%= link_to user_path(current_user) do%>
      <i class="fas fa-user" style="color: white; margin-left: 8px;font-size: 24px;"></i>
      <% end %>
      <% else %>
      <%= link_to new_user_session_path do%>
      <i class="fas fa-user" style="color: white; margin-left: 8px;font-size: 24px;"></i>
      <% end %>
      <% end %>
    </div>
  </div>
</div>
</nav>



<script>
  const onClick = () => {
    const crossButton = document.querySelector('.cross');
    const menuButton = document.querySelector('.menu');
    crossButton.classList.toggle('block');
    menuButton.classList.toggle('transparent');
  }
</script>

<style>
  .icon {
    font-size: 24px;
  }
</style>

app/views/shared/_social.html.erb
<div class="social-banner" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://res.cloudinary.com/dokddymx6/image/upload/v1591538971/Captura_de_Pantalla_2020-06-07_a_la_s_11.06.14_mfxvby.jpg);">
  <%= link_to 'https://www.instagram.com/tilotiendanatural/' , target: '_blank' do  %>
  <h2 class="text-center"><i class="fab fa-instagram"></i> tilotiendanatural</h2>
  <div class="social-container">
    <img src="https://res.cloudinary.com/dokddymx6/image/upload/v1591539000/Captura_de_Pantalla_2020-06-07_a_la_s_11.08.31_uv0lnr.jpg" alt="">
    <img src="https://res.cloudinary.com/dokddymx6/image/upload/v1591538999/Captura_de_Pantalla_2020-06-07_a_la_s_11.08.17_ypkxd8.jpg" alt="">
    <img src="https://res.cloudinary.com/dokddymx6/image/upload/v1591538993/Captura_de_Pantalla_2020-06-07_a_la_s_11.07.31_vcu4xx.jpg" alt="">
    <img src="https://res.cloudinary.com/dokddymx6/image/upload/v1591799182/Captura_de_Pantalla_2020-06-10_a_la_s_11.19.19_w99wgc.jpg" alt="">
    <img src="https://res.cloudinary.com/dokddymx6/image/upload/v1591539700/Captura_de_Pantalla_2020-06-07_a_la_s_11.20.53_pvkgfb.jpg" alt="" class="">
    <img src="https://res.cloudinary.com/dokddymx6/image/upload/v1591538992/Captura_de_Pantalla_2020-06-07_a_la_s_11.06.57_m2cgrt.jpg" alt="">
  </div>
  <% end %>
</div>

app/views/shared/_topbar.html.erb
<div class="topbar-container d-sm-flex align-items-center justify-content-center text-center">
  <p><div><i class="fas fa-truck"></i><strong> Envio gratis en compras superiores a $6000</strong></div><small>*dentro de San Nicolás</small></p>
</div>
<div class="topbar-sub-container text-center">
  <p class=""> <small>*Lista de precios orientativa!!</small></p>
</div>