config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  post 'procesar-pago', to: "payments#create"
  get 'pages/search', to: 'pages#search'
  get 'products/search', to: 'products#search'
  get '/info', to: 'pages#info'

  resources :divisions, except: :destroy
  resources :categories, except: :destroy
  resources :products
  resources :users, only: [:index, :show]
  resources :line_items
  resources :carts do
    collection do
      post :carts_delete
    end
  end
  resources :orders, only: [:index, :show, :create] do
    resources :payments, only: :new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :line_items, dependent: :destroy
  monetize :price_cents
  paginates_per 12

  validates :title, presence: true
  validates :description, presence: true
  validates :stock, presence: true
  has_many_attached :photos
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :search]
  before_action :set_products, only: [:show, :update, :destroy]

  def index
    @categories = Category.order(title: :asc)
    if current_user.admin?
      @products = Product.all
      if params["category_id"]
        @products = Product.where(category_id: params["category_id"]).order(price_cents: :asc)
      elsif params["price_cents"]
        @products = Product.order(price_cents: :desc)
      else
        @products
      end
    else
      redirect_to root_path
      flash[:notice] = "Accesso denegado!"
    end
  end

  def show
    @products = Product.all
    @guillo = Product.where
  end

  def new
    if current_user.admin?
      @product = Product.new
    else
      redirect_to root_path
      flash[:notice] = "Accesso denegado!"
    end
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    if current_user.admin?
      @product = Product.find(params[:id])
    else
      redirect_to root_path
      flash[:notice] = "Accesso denegado!"
    end
  end

  def update
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def search
    if params[:query].present?
      sql_query = " \
      products.title @@ :query \
      OR categories.title @@ :query \
      "
      @products = Product.joins(:category).where(sql_query, query: "%#{params[:query]}%")
    else
      @products = Product.all
    end
  end

  private

  def set_products
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :stock, :brand, :flavor, :condition, :vegan, :sale, :sugar, :capacity, :category_id, photos: [])
  end
end

app/views/products/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @product.photos.first(1).each_with_index do |photo, index| %>
    <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="active"></li>
    <% end %>
    <% @product.photos.drop(1).each_with_index do |photo, index| %>
    <li data-target="#carouselExampleIndicators" data-slide-to="<%= index + 1 %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% @product.photos.first(1).each do |photo| %>
    <div class="carousel-item active">
      <%= cl_image_tag photo.key %>
    </div>
    <% end %>
    <% @product.photos.drop(1).each do |photo| %>
    <div class="carousel-item">
      <%= cl_image_tag photo.key %>
    </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
<p>Nombre</p>
<%= f.input :title, label: false %>
<p>Descripcion</p>
<%= f.input :description, label: false %>
<p>Foto</p>
<%= f.input :photos, as: :file, input_html: { multiple: true } %>
<p>Precio</p>
<%= f.input :price, label: false, input_html: { class: 'form-control form-control-lg'} %>
<p>Oferta (poner aca el precio mas alto)</p>
<%= f.input :sale, label: false %>
<p>Tamaño (poner solo en los productos con diferentes tamaños)</p>
<%= f.input :flavor, label: false, collection: ["100 gr.", "200 gr.",
"250 gr.", "400 gr.", "500 gr.", "1 kilo", "2 kilos", "5 kilos", "1 lt", "200 ml", "500 ml" ] %>
<p>Stock</p>
<%= f.input :stock, label: false %>
<p>Marca</p>
<%= f.input :brand, label: false , collection: ["Beepure",
"La Francia",
"Murke",
"Las Quinas",
"Doña Magdalena",
"Cuarto Creciente",
"Le Fit",
"Fit Fruit",
"Zafran",
"Delicel",
"Integralia",
"Cachafaz",
"Quaker",
"Deluxe",
"Integra",
"Mate & Co",
"Famiglia Dell'Isola",
"Recetas de Entonces Gourmet ",
"Pampa Gourmet",
"Cristo del Cerro",
"Ricco",
"Inti zen",
"Natier",
"Dicomere",
"Heredia",
"Chamana",
"Felices las Vacas",
"Prasat",
"Leofanti",
"Carmela Tomasa",
"Sentida Botanica",
"Veganitas",
"Veganis",
"Sri Sri"
]%>
<p>Sabor</p>
<%= f.input :capacity, label: false, collection: ["naranja",
"limón",
"vainilla",
"chocolate",
"coco",
"avena",
"cacao",
"salvado con sal",
"salvado sin sal",
"dulces",
"original",
"chocolate sin azucar",
"chocolate negro",
"chocolate blanco"] %>
<p>Celíaco</p>
<%= f.input :condition, label: false, collection: ['Celíaco'] %>
<p>Vegano</p>
<%= f.input :vegan, label: false, collection: ['Vegano'] %>
<p>Diabético</p>
<%= f.input :sugar, label: false, collection: ['Diabético'] %>
<p>Categoría</p>
<%= f.association :category, label: false %>
<%= f.submit 'Crear Producto', class: 'btn btn-product btn-lg btn-block' %>
<% end %>

app/views/products/_product_content.html.erb
<div class="product-navbar d-flex">
  <p>Inicio</p>
  <p>></p>
  <p><%= @product.category.division.title %></p>
  <p>></p>
  <p><%= @product.category.title %></p>
</div>
<div class="product-title">
  <h2><%= @product.title.upcase %></h2>
  <div class="quantity-product-container">
   <% if @product.flavor.present? %>
   <div class="dropdown">
    <a class="btn btn-dropdown dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= @product.flavor %>
    </a>
    <% product_title =  @product.title %>
    <% product_links = @products.filter { |product| product.title == product_title } %>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <% product_links.each do |g| %>

      <%= link_to  g.flavor, product_path(g), class: 'dropdown-item' %>
      <% end %>
    </div>
  </div>
  <br>
  <% else %>
  <% end %>
</div>




<div class="d-flex">
  <% if @product.sale.present? %>
  <h3 style="color: red; font-weight: bold;"><%= humanized_money_with_symbol(@product.price) %></h3>
  <h3 style="padding-left: 10px; text-decoration: line-through; color: lightgrey;">$<%= @product.sale %></h3>
  <% else %>
  <h3><%= humanized_money_with_symbol(@product.price) %></h3>
  <% end %>
</div>
<% if @product.stock >= 1 %>
<%= form_tag line_items_path do %>
<%= hidden_field_tag 'product_id', @product.id %>
<%= submit_tag 'AGREGAR AL CARRITO', class: 'btn btn btn-lg btn-product btn-block' %>
<% end %>
<% else %>
<button class="btn btn btn-lg btn-dark btn-block">AGOTADO</button>
<% end %>
</div>
<div class="product-content">
  <div class="d-flex justify-content-between align-items-center product-show-list" id="button" onclick="showElement()">
    <p>Detalles del producto</p>
    <p id="plus">+</p>
  </div>
  <div class="none product-show-list-hide" id="show">
    <p><%= @product.description %></p>
  </div>
  <div class="d-flex justify-content-between align-items-center product-shop-list" id="howtoshop" onclick="showElementSecondary()">
    <p>Como comprar</p>
    <p id="sum">+</p>
  </div>
  <div class="none product-show-list-hide" id="shop">
    <p>El pago se puede hacer mediante <strong>transferencia bancaria</strong>  o en <strong>efectivo</strong> ya sea durante la entrega del producto en tu domicilio o abonando en el local.</p>
    <p><strong>Por el momento el pago con tarjetas no esta disponble</strong></p>
  </div>
</div>

<script>
  const showElement = () => {
    const minus = document.getElementById('plus');
    if (minus.innerText === '+') {
      minus.innerText = '-'
    } else {
      minus.innerText = '+'
    };
    const border = document.querySelector('.product-show-list');
    border.classList.toggle("border-transparent")

    const button = document.querySelector('#show');
    button.classList.toggle("show");
  }

  const showElementSecondary = () => {
    const minus = document.getElementById('sum');
    if (minus.innerText === '+') {
      minus.innerText = '-'
    } else {
      minus.innerText = '+'
    };
    const border = document.querySelector('.product-shop-list');
    border.classList.toggle("border-transparent")

    const button = document.querySelector('#shop');
    button.classList.toggle("show");
  }

</script>

app/views/products/edit.html.erb
<%= render 'shared/navbar' %>
<br><br><br>
<div class="product-form">
  <h3><%= link_to 'Volver a la pagina principal', root_path  %></h3>
  <h2>Editar Producto</h2>
  <%= render 'form' %>
</div>

app/views/products/index.html.erb
<%= render 'shared/navbar' %>
<div class="product-stock-wrapper">
  <div class="index-filters text-center d-md-flex justify-content-around">
    <p><%= link_to "ORDENAR POR PRECIO", products_path(price_cents: :desc), class: 'btn btn-dark' %></p>
    <p> <button type="button" class="btn btn-product" data-toggle="modal" data-target="#exampleModalLong">
      FILTRAR POR CATEGORIA
    </button></p>
  </div>
  <table class="table table-striped table-bordered text-center">
    <thead class="thead-dark">
      <tr>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Stock</th>
        <th>Categoria</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.stock%></td>
        <td><%= product.category.title %></td>

        <td><%= link_to 'Editar', edit_product_path(product)  %> </td>
        <td><%= link_to 'Eliminar', product_path(product),  method: :delete,  data: { confirm: 'Are you sure?' }  %> </td>
        <td><%= link_to 'Ver', product_path(product) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="p-3">
    <%= link_to 'Crear Producto', new_product_path, class: 'btn btn-primary btn-block' %>
    <br>
    <%= link_to 'Volver', user_path(current_user), class: 'btn btn-danger btn-block' %>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Categorias</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @categories.each do |category| %>
        <p><%= link_to category.title , products_path(category_id: category.id) %></p>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark btn-lg btn-block" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'shared/navbar' %>
<div class="product-form">
  <h3><%= link_to 'Volver a la pagina principal', root_path  %></h3>
  <h2>Crear Producto</h2>
  <%= render 'form' %>
</div>

app/views/products/search.html.erb
<%= render 'shared/navbar' %>
<div class= "product-search-wrapper">
  <h5><strong>Resultados</strong> (<%= @products.uniq(&:title).count %>)</h4>
    <div class= "division-container ">
      <% @products.uniq(&:title).each do |product| %>
      <%= render 'shared/cards', product: product %>
      <% end %>
    </div>
    <div class="p-5 text-center">
      <div class="p-5">
       <%= link_to 'INICIO', root_path , class: 'btn btn-block btn-product' %>
     </div>
   </div>
 </div>

app/views/products/show.html.erb
<%= render 'shared/navbar' %>
<div class="product-show-wrapper">
  <div class="product-image">
    <%= render 'carousel' %>
  </div>
  <div class="product-description">
   <%= render 'product_content' %>
 </div>
</div>
<div class="product-footer">
  <h2>PRODUCTOS RELACIONADOS</h2>
  <div class="scrolling-wrapper">
    <div class="home-card-container">
      <% @products.last(5).uniq(&:title).each do |product| %>
      <%= render 'shared/home_cards', product: product %>
      <% end %>
    </div>
  </div>
</div>